FROM node:20-alpine AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY package.json package-lock.json* ./
COPY packages/ ./packages/
COPY apps/web/ ./apps/web/
COPY tsconfig.base.json ./

ENV API_URL=http://api:4000

RUN npm install
RUN mkdir -p apps/web/public
RUN npm --workspace=packages/types run build
RUN npm --workspace=packages/shared run build
RUN npm --workspace=packages/validation run build
RUN npm --workspace=apps/web run build

FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0
ENV API_URL=http://api:4000

COPY --from=builder /app/package.json ./
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/apps/web/.next ./apps/web/.next
COPY --from=builder /app/apps/web/public ./apps/web/public
COPY --from=builder /app/apps/web/package.json ./apps/web/package.json

EXPOSE 3000

CMD ["npm", "--workspace=apps/web", "run", "start"]
